### ISSUE TITLE
launchpad not work on premise

### ISSUE THREAD

**Issue by dcriaco** [abap2UI5/abap2UI5-launchpad_on_premise#9]
Hi,
I created an app demo and I would to link on my launchpad.
I followed the guide but still get errors:
![Screenshot 2024-01-04 104952](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/155626415/cad90c73-390c-45a1-97c4-052e00a6105a)

thanks in advance.
kind regards.
domenico

**Comment by oblomov-dev** [comment]
hi domenico,

can you jump to this position and make a screenshot form the source code:
<img width="802" alt="image" src="https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/102328295/2638227f-2eab-4b5f-af46-b140aa6fdcd1">

Best regards.

**Comment by dcriaco** [comment]
Hi oblomov,
I assume you need this screen
![Screenshot 2024-01-04 112100](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/155626415/424162e4-6ace-4cbb-8c14-c532694b0f92)
![Screenshot 2024-01-04 112218](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/155626415/25d311e8-2dae-443b-b885-17c04b7f27bd)

Anyway I attached all source code
[abap.txt](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/files/13828749/abap.txt)

Best regards.

**Comment by oblomov-dev** [comment]
ok not sure what is happening there... can you also press on VM1170:1, i think there you should see also some JS send from the backend which creates the error. If you see nothing, start debugging tools before pressing refresh.

**Comment by dcriaco** [comment]
"undefined" is not valid JSON

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at f (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:431:1372)
    at t (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:431:3325)
    at Object.U [as on] (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:431:7046)
    at a.<computed> [as on] (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/core-min-0.js:19:343)
    at b.init (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/core-min-1.js:76:1906)
    at http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:149:2979
    at f.constructor (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:149:3063)
    at f.constructor (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:161:1195)
    at f.constructor (http://xxx:1111/sap/bc/ui5_ui5/ui2/ushell/resources/~20191120123400~/sap/ushell_abap/bootstrap/evo/abap.js:159:999)

**Comment by oblomov-dev** [comment]
seems the JSON.parse is the problem, can you jump to the source code position of this command. you can just press VM1170:1 and then you should be on the source code position. there you can set a breakpoint and check the content of the parse command. 

You use the latest abap2UI5 and abap2UI5-launchpad version?

**Comment by dcriaco** [comment]
Sorry Oblomov but I'm not  an expert in web development.
When I press VM... I obtain a strange long string that begins with:
&#xa;sap.ui.core.BusyIndicator.show&#x28;&#x29;&#x3b;&#xa;sap.ui.getCore&#x28;&#x29;.attachInit&#x28;&#x2

I dowloaded  abap2ui5 and abap2ui5-launchpad  last week.

**Comment by dcriaco** [comment]
good morning Oblomov,
I followed yours instructions and unfortunately doesn't work.
![Screenshot 2024-01-05 094732](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/155626415/3514e39e-10b3-413d-a375-d8e6d739d2b3)

When I try directly with url works fine.

best regards,
Domenico

**Comment by oblomov-dev** [comment]
Hi @dcriaco,

ok that looks interesting, so far i have no idea. Maybe something with the UI5 version is not working properly, I updated abap2UI5 and the launchpad repository. Can you install the latest version of both one more time?

I am sure you use chrome as browser right?

Best regards.
